#version: "3"

services:
  main:
    image: franka_ros:latest
    build: .docker
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./packages:/catkin_ws/src/dir_name  # edit this as you want!
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: bash --login
